name: meal_maestro
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^1.2.0
  cloud_firestore: ^2.2.0
  firebase_messaging: ^10.0.2
  firebase_storage: ^10.0.1
  firebase_analytics: ^8.3.0
  firebase_auth: ^3.0.1
  google_sign_in: ^5.0.4
  firebase_crashlytics: ^2.2.1
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
flutter:
  uses-material-design: true